#
# IDF2PHPP: A Plugin for exporting an EnergyPlus IDF file to the Passive House Planning Package (PHPP). Created by blgdtyp, llc
# 
# This component is part of IDF2PHPP.
# 
# Copyright (c) 2020, bldgtyp, llc <info@bldgtyp.com> 
# IDF2PHPP is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published 
# by the Free Software Foundation; either version 3 of the License, 
# or (at your option) any later version. 
# 
# IDF2PHPP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.
# 
# For a copy of the GNU General Public License
# see <http://www.gnu.org/licenses/>.
# 
# @license GPL-3.0+ <http://spdx.org/licenses/GPL-3.0+>
#
"""
Takes in a list of Honeybee zones and outputs print-ready (floor plan) objects for the Treated Floor Area (TFA). Will pull out any 'PHPP Room' information from the zones and create surfaces, color them by TFA factor, and create room-tags based on the data. Be sure you've used the 'Create PHPP Rooms' to assign parameters to the zones and geometry correctly before trying to use this.
-    
    Args:
        _thermalBridges:
        highlightSize_: (float) Default 0.07 - print weight for the TB Curve
        highlightColor_: (Color) To color the TB Curve highlight for printing
    Returns:
        filenames_: A list of autogenerated Filenames for use if you want.
        geom_: A Tree of the TB geometry where each branch is a different curve.
        pageLabels_: Some text info that can be printed on the Layout page if you want.
"""

ghenv.Component.Name = "BT_2PDF_TBs"
ghenv.Component.NickName = "2PDF | Thermal Bridges"
ghenv.Component.Message = 'JUN_07_2020'
ghenv.Component.IconDisplayMode = ghenv.Component.IconDisplayMode.application
ghenv.Component.Category = "BT"
ghenv.Component.SubCategory = "03 | PDF"

from System import Object
from Grasshopper import DataTree
from Grasshopper.Kernel.Data import GH_Path
import ghpythonlib.components as ghc

geom_ = DataTree[Object]()
pageLabels_ = DataTree[Object]()
filenames_ = []

rad = highlightSize_ if highlightSize_ else 0.1
highlightC = highlightColor_ if highlightColor_ else ghc.ColourRGB(255,255,255,183)

if len(_thermalBridges) > 0:
    for i, tb in enumerate(_thermalBridges):
        
        if tb.geometry == None:
            break
        
        # Add the highlight Geometry to the Tree
        geom = ghc.Pipe(tb.geometry, rad, 2)
        geom = ghc.MeshColours(geom, highlightC)
        geom_.Add(geom, GH_Path(i))
        
        # Add the Text
        txt = []
        txt.append('{}-{}'.format(tb.IDNumber, tb.Name))
        txt.append( 'Length: {:.2f} m'.format(tb.Length))
        txt.append( 'Group: {}'.format(tb.GroupNo))
        txt.append( 'fRsi: {}'.format(tb.fRSI if tb.fRSI else '-'))
        pageLabels_.AddRange(txt, GH_Path(i))
        
        # Add the filename
        filenames_.append('TB_DIM_{}-{}'.format(tb.IDNumber, tb.Name))
